version: '3.7'

services:
  postgres:
    image:  postgres:13-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgres/data
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: Tom
      POSTGRES_PASSWORD: Tom123